version: 2
updates:
  - package-ecosystem: "github-actions"
    labels:
      - 📦 dependencies # add this label in the repository
    directory: / # location of package.json in the repository
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
