name: "📚 Documentation"
description: Report a documentation deficiency to help improve the project. Or Suggestions for new workflow.
title: "📚 [Documentation] - Title"
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        📚 **Document Updation / Workflow Suggestion**

        Thanks for taking the time to fill out this documentation deficiency report! :memo:
  - type: textarea
    id: description
    attributes:
      label: "Description of the documentation deficiency / workflow suggestion. ✍🏻"
      description: Please provide a clear and concise description of what the documentation deficiency / workflow suggestion is.
      placeholder: Short and explicit description of the documentation deficiency / workflow suggestion...
    validations:
      required: true
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing [issues](https://github.com/CatsInTech/GitHub-ReadMe/issues)"
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/CatsInTech/GitHub-ReadMe/blob/main/CONTRIBUTING.md)"
          required: true

        - label: "I am willing to work on this issue (optional)"
          required: false

        - label: "I am a GSSoC'23 contributor"
          required: false
