name: Build and Push Docker Image
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME = ${{ github.repository_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log in to Registry
        run: echo "${{ secrets.G_TOKEN }}" | docker login https://ghcr.io -u {{ github.actor }} --password-stdin
          
      - name: Build and Push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_ID

